# -*- coding: utf-8 -*-
"""Matplotlib-imshow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zUiTEvPheyvFQQsyyx1WmSUPqq4dEZx

Matplotlib의 imshow는 원하는 사이즈의 픽셀을 원하는 색을 채워서 만든 그림이다.\
각 칸을 채우는 방법에는 4가지가 있다.


> 1) colormap 디폴트\
2) colotmap 변경\
3) RGB\
4) RGBA
"""

#Import module
import numpy as np
import matplotlib.pyplot as plt

"""##Colormap Default

colormap의 dafault 값은 viridis로 보라색과 노란색이 나타난다.\
기본적으로 colormap은 입력된 숫자를 0~1 사이의 normalize하여 색으로 나타낸다.
"""

Z = np.array([[10,0,0,0,0],[0,10,0,0,0],[0,0,10,0,0],[0,0,0,10,0],[0,0,0,0,10]])
plt.imshow(Z)
plt.show()

Y = np.array([[10,0,0,0,5],[0,10,0,5,0],[0,0,10,0,0],[0,5,0,10,0],[5,0,0,0,10]])
plt.imshow(Y)
plt.show()

X = np.array([[20,5,2],[2,20,3],[11,2,20]])
plt.imshow(X)
plt.show()

"""##Colormap 변경방법"""

import matplotlib.cm as cm

W = np.array([[20,5,2],[2,20,3],[11,2,20]])
plt.imshow(W, cmap = cm.gray)
plt.show()

"""##RGB

행렬의 각 원소로 [R,G,B]값을 0-255 또는 0-1 사이의 값을 입력하면 된다.
"""

V = np.array(
[
     [[255,0,0],[255,0,0],[255,0,0]],
     [[0,255,0],[0,255,0],[0,255,0]],
     [[0,0,255],[0,0,255],[0,0,255]]
])
plt.imshow(V)
plt.show()

U = np.array(
[
     [[1,0,0],[0.65,0,0],[0.35,0,0]],
     [[0,0.35,0],[0,1,0],[0,0.65,0]],
     [[0,0,0.35],[0,0,0.65],[0,0,1]]
])
plt.imshow(U)
plt.show()

"""##RGBA

RGBA의 A는 투명도를 나타내며, [R,G,B,A]를 각 행렬의 원소로 입력한다.\
값은 RGB와 동일하네 0-1 또는 0-255 사이의 값을 입력한다.
"""

T = np.array(
[
     [[255,0,0,0.2],[255,0,0,0.5],[255,0,0,1]],
     [[0,255,0,0.2],[0,255,0,0.5],[0,255,0,1]],
     [[0,0,255,0.2],[0,0,255,0.5],[0,0,255,1]]
])
plt.imshow(T)
plt.show()